const Menus = [
  {
    // branchId:?
    name: "ACID PHOSPHATASE",
    abbreviation: "ACP",
    packages: [46],
    discountable: true,
    TAT: 2,
    is_profile: false,
    opd: 0, // SUGGESTED RETAIL PRICE
    hmo: 0, // Health Maintenance Organization
    er: 0,
    cw: 0, // charity ward
    pw: 0, // Private ward
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: false,
  },
  {
    name: "ACTIVATED PARTIAL THROMBOPLASTIN TIME",
    abbreviation: "aPTT",
    packages: [54],
    discountable: 1,
    TAT: 1,
    is_profile: false,
    opd: 100,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "ACTUAL PLATELET COUNT",
    abbreviation: "APC",
    packages: [59],
    discountable: 1,
    TAT: 0,
    is_profile: false,
    opd: 100,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "ALKALINE PHOSPHATASE",
    abbreviation: "ALP",
    packages: [31],
    discountable: 1,
    TAT: -1,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "ALBUMIN",
    abbreviation: "ALB",
    packages: [36],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "ALDOSTERONE",
    abbreviation: "ALD",
    packages: [39],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "ALPHA FETO PROTEIN Quantitative",
    abbreviation: "AFP",
    packages: [130],
    discountable: 1,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "AMYLASE",
    abbreviation: "AMY",
    packages: [52],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "ANTI CARDIOLIPIN IGG",
    packages: [141],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "ANTI CARDIOLIPIN IGM",
    packages: [142],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "ANTIBODY SCREENING",
    packages: [55],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "mk",
    packages: [132],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "ANA",
    packages: [107],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "ASO Titer",
    packages: [135],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "APTS TEST",
    packages: [85],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "B-HCG QUANTI",
    packages: [136],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FINE NEEDLE ASPIRATION BIOPSY",
    abbreviation: "FNAB",
    packages: [170],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FINE NEEDLE ASPIRATION BIOPSY /ADDITIONAL SLIDE",
    abbreviation: "FNAB /ADDITIONAL SLIDE",
    packages: [171],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "BIOPSY SMALL /<5 CM",
    abbreviation: "BIOPSY SMALL",
    packages: [172],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "BIOPSY MEDIUM /5.1-10 CM",
    abbreviation: "BIOPSY MEDIUM",
    packages: [173],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "BIOPSY LARGE /10.1-20 CM",
    abbreviation: "BIOPSY LARGE",
    packages: [174],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "BIOPSY XL /20 CM ABOVE",
    abbreviation: "BIOPSY XL",
    packages: [175],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    serviceId: null,
    name: "BIOPSY LEVEL I - PF",
    abbreviation: "BIOPSY LEVEL I - PF",
    packages: [175],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "BIOPSY LEVEL II - PF",
    abbreviation: "BIOPSY LEVEL II - PF",
    packages: [175],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    serviceId: null,
    name: "BIOPSY LEVEL III - PF",
    abbreviation: "BIOPSY LEVEL III - PF",
    packages: [8],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    serviceId: null,
    name: "BIOPSY LEVEL IV - PF",
    abbreviation: "BIOPSY LEVEL IV - PF",
    packages: [105, 215, 26],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "BLOOD TYPING  + RH",
    abbreviation: "BT/RH",
    packages: [8],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "BLOOD BAGS 1/ SINGLE",
    abbreviation: "BAG/S",
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "BLOOD BAGS 2/ DOUBLE",
    abbreviation: "BAG/D",
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "BLOOD BAGS 3/ TRIPLE",
    abbreviation: "BAG/T",
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "CULTURE AND SENSITIVITY BOTTLE /BLOOD",
    abbreviation: "C/S BOTTLE",
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "CULTURE AND SENSITIVITY /BLOOD PROCESSING only",
    abbreviation: "C/S PROCESSING",
    packages: [106, 107],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "BLD C/S",
    packages: [8],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "BLOOD HANDLING FEE",
    abbreviation: "HANDLING FEE",
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "BLOOD PROCESSING FEE",
    abbreviation: "PROCESSING FEE",
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "ABO/RH",
    packages: [66],
    discountable: 1,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "BLOOD UREA NITROGEN",
    abbreviation: "BUN",
    packages: [20],
    discountable: 1,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "BLOOD URIC ACID",
    abbreviation: "BUA",
    packages: [12],
    discountable: 1,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "BODY FLUID C/C",
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "BODY FLUIDS G/S",
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "CA 15-3",
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "CARCINOEMBRYONIC ANTIGEN/ COLORECTAL CA",
    abbreviation: "CEA",
    packages: [88],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "CARDIAC PROFILE",
    abbreviation: "CARDIAC PROFILE",
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "CELL BLOCK",
    abbreviation: "CELL BLOCK",
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "CELL BLOCK -PF",
    abbreviation: "CELL BLOCK -PF",
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "TOTAL CHOLESTEROL",
    abbreviation: "TC",
    packages: [13],
    discountable: 1,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "CLOTTING TIME",
    abbreviation: "CT",
    packages: [61],
    discountable: 1,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    serviceId: null,
    name: "CLOTTING TIME/BLEEDING TIME",
    abbreviation: "CT/BT",
    packages: [60, 61],
    discountable: 1,
    TAT: 0,
    is_profile: true,
    opd: 100,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "COMPLEMENT 3",
    abbreviation: "C3",
    packages: [124],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "COMPLEMENT 4",
    abbreviation: "C4",
    packages: [125],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "CBC",
    packages: [58],
    discountable: 1,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "COMPLETE BLOOD COUNT W/ PLATELET",
    abbreviation: "CBC/APC",
    packages: [58, 59],
    discountable: 1,
    TAT: 0,
    is_profile: true,
    opd: 250,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "CORTISOL",
    abbreviation: "CORTISOL",
    packages: [129],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "CPK-MB/CK-MB",
    packages: [78],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "CPK-MM/CK-MM",
    packages: [79],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "CREATININE /24 HR URINE",
    abbreviation: "CREA /24 HR URINE",
    packages: [81],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "CRP QUALI",
    packages: [137],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "C-REACTIVE PROTEIN/ QUANTITATIVE",
    abbreviation: "CRP QUANTI",
    packages: [155, 48],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "CREATININE",
    abbreviation: "CREA",
    packages: [19],
    discountable: 1,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "CREATININE CLEARANCE",
    abbreviation: "CREATININE CLEARANCE",
    packages: [81],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "X-MATCH",
    packages: [56],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: true,
    is_available: true,
  },
  {
    name: "CRYOPRECIPITATE",
    abbreviation: "CRYO",
    packages: [8],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "C/S",
    packages: [8],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: true,
    is_available: true,
  },
  {
    name: "CYTOMEGALO VIRUS SCREENING",
    abbreviation: "CYTOMEGALO VIRUS",
    packages: [90],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "DENGUE DUO (AG/AB) TEST",
    abbreviation: "NS1, IgG & IgM",
    packages: [77],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "PACKAGE 1",
    abbreviation: "P1",
    packages: [10, 13, 14, 15, 16, 17, 18],
    discountable: 0,
    TAT: 0,
    is_profile: true,
    opd: 750,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "PACKAGE 2",
    abbreviation: "P2",
    packages: [10, 12, 13, 14, 15, 16, 17, 18, 19, 21, 58, 143],
    discountable: 0,
    TAT: 0,
    is_profile: true,
    opd: 900,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "PACKAGE 3",
    abbreviation: "P3",
    packages: [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
    discountable: 0,
    TAT: 0,
    is_profile: true,
    opd: 1200,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "PACKAGE 4",
    abbreviation: "P4",
    packages: [8],
    discountable: 0,
    TAT: 0,
    is_profile: true,
    opd: 1300,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "PACKAGE 5",
    abbreviation: "P5",
    packages: [135],
    discountable: 0,
    TAT: 0,
    is_profile: true,
    opd: 2900,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "POTASSIUM",
    abbreviation: "K+",
    packages: [23],
    discountable: 1,
    TAT: -1,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "SODIUM",
    abbreviation: "Na+",
    packages: [25],
    discountable: 1,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "CHLORIDE",
    abbreviation: "Cl-",
    packages: [24],
    discountable: 1,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "CALCIUM",
    abbreviation: "Ca++",
    packages: [27],
    discountable: 1,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "CALCIUM,  IONIZE",
    abbreviation: "iCa++",
    packages: [28],
    discountable: 1,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "ELECTROLYTES 1/ (NA/K/CL)",
    abbreviation: "NA/K/CL",
    packages: [25, 23, 24],
    discountable: 1,
    TAT: 0,
    is_profile: true,
    opd: 1000,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "ELECTROLYTES 2/ (NA/K/iCa++)",
    abbreviation: "NA/K/iCa++",
    packages: [25, 23, 28],
    discountable: 1,
    TAT: 0,
    is_profile: true,
    opd: 1000,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "ELECTROLYTES 3/ (NA/K/CL/iCa++)",
    abbreviation: "NA/K/CL/iCa++",
    packages: [25, 23, 24, 28],
    discountable: 1,
    TAT: 0,
    is_profile: true,
    opd: 1200,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "ERYTHROCYTE SEDIMENTATION RATE",
    abbreviation: "ESR",
    packages: [63],
    discountable: 1,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "ER PR W/ HER 2 NEU",
    packages: [8],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "ER",
    packages: [8],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "EXTRACTION FEE / COAGULATION",
    abbreviation: "EXTRACT",
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: false,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FACTOR 8",
    abbreviation: "FACTOR 8",
    packages: [143],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "ACID FAST BACILLI STAIN",
    abbreviation: "AFB",
    packages: [5],
    discountable: 1,
    TAT: 0,
    is_profile: false,
    opd: 250,
    refund: 180,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FECALYSIS",
    abbreviation: "F/A",
    packages: [83],
    discountable: 1,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "FERRITIN",
    packages: [99],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "Fluid Analysis",
    packages: [100],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FLUIDS CELL COUNT",
    abbreviation: "BODY FLUIDS CELL COUNT",
    packages: [49],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FLUIDS GLUCOSE",
    abbreviation: "BODY FLUIDS GLUCOSE",
    packages: [184],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FLUIDS PROTEIN",
    abbreviation: "BODY FLUIDS PROTEIN",
    packages: [154],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FOLLICLE STIMULATING HORMONE",
    abbreviation: "FSH",
    packages: [98],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "THYROID STIMULATING HORMONE",
    abbreviation: "TSH",
    packages: [110],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FREE TRIIODOTHYRONINE",
    abbreviation: "FT3",
    packages: [111],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FREE TETRAIODOTHYRONINE/ THYROXINE",
    abbreviation: "FT4",
    packages: [112],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "Triiodothyronine",
    abbreviation: "T3",
    packages: [113],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "TETRAIODOTHYRONINE/ THYROXINE",
    abbreviation: "T4",
    packages: [114],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "Thyroid Screening",
    abbreviation: "TS",
    packages: [110, 113, 114],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "Thyroid Monitoring",
    abbreviation: "TM",
    packages: [110, 111, 112],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FRESH FROZEN PLASMA",
    abbreviation: "FFP",
    packages: [162],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FRESH PLASMA",
    abbreviation: "FP",
    packages: [8],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FRESH WHOLE BLOOD",
    abbreviation: "FWB",
    packages: [46],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: true,
    is_available: true,
  },
  {
    name: "GAMMA GLUTAMYL TRANSPEPTIDASE",
    abbreviation: "GGTP",
    packages: [157],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "G6PD ASSAY",
    packages: [50],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "G6PD CONFIRMATORY",
    packages: [73],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "GLYCOSYLATED HEMOGLOBIN",
    abbreviation: "HbA1c",
    packages: [11],
    discountable: 1,
    TAT: -1,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "G/S",
    packages: [160],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "HELICOBACTER PYLORI IGM (Quali)",
    abbreviation: "H.PYLORI IGM",
    packages: [216],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "HELICOBACTER PYLORI IGM (Quanti)",
    abbreviation: "H.PYLORI QUANTI",
    packages: [8],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "HEMOGLOBIN ELECTROPHORESIS",
    abbreviation: "Hgb ELECTROPHORESIS",
    packages: [8],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "HEMOGLOBIN/ HEMATOCRIT",
    abbreviation: "Hgb/Hct",
    packages: [219],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    serviceId: null,
    abbreviation: "Hct/APC",
    packages: [58, 59],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: null,
    abbreviation: "ANTI-HAV IGG",
    packages: [43],
    discountable: 1,
    TAT: -1,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "ANTI HEPATITIS A VIRUS IGM",
    abbreviation: "ANTI-HAV IGM",
    packages: [49],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FLUIDS CELL COUNT",
    abbreviation: "BODY FLUIDS CELL COUNT",
    packages: [49],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FLUIDS CELL COUNT",
    abbreviation: "BODY FLUIDS CELL COUNT",
    packages: [49],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FLUIDS CELL COUNT",
    abbreviation: "BODY FLUIDS CELL COUNT",
    packages: [49],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FLUIDS CELL COUNT",
    abbreviation: "BODY FLUIDS CELL COUNT",
    packages: [49],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FLUIDS CELL COUNT",
    abbreviation: "BODY FLUIDS CELL COUNT",
    packages: [49],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FLUIDS CELL COUNT",
    abbreviation: "BODY FLUIDS CELL COUNT",
    packages: [49],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FLUIDS CELL COUNT",
    abbreviation: "BODY FLUIDS CELL COUNT",
    packages: [49],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FLUIDS CELL COUNT",
    abbreviation: "BODY FLUIDS CELL COUNT",
    packages: [49],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FLUIDS CELL COUNT",
    abbreviation: "BODY FLUIDS CELL COUNT",
    packages: [49],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FLUIDS CELL COUNT",
    abbreviation: "BODY FLUIDS CELL COUNT",
    packages: [49],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FLUIDS CELL COUNT",
    abbreviation: "BODY FLUIDS CELL COUNT",
    packages: [49],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FLUIDS CELL COUNT",
    abbreviation: "BODY FLUIDS CELL COUNT",
    packages: [49],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FLUIDS CELL COUNT",
    abbreviation: "BODY FLUIDS CELL COUNT",
    packages: [49],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "FLUIDS CELL COUNT",
    abbreviation: "BODY FLUIDS CELL COUNT",
    packages: [49],
    discountable: 0,
    TAT: 0,
    is_profile: false,
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    promo: 0,
    has_reseco: true,
    refund: 0,
    render_tags: null,
    is_unique: false,
    is_available: true,
  },
  {
    name: "BIOPSY Profesional Fee",
    abbreviation: "BIOPSY pf",
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    is_unique: false,
    is_available: true,
  },
  {
    name: "Service Charge",
    abbreviation: "SC",
    opd: 0,
    hmo: 0,
    er: 0,
    cw: 0,
    pw: 0,
    is_unique: false,
    is_available: true,
  },
];

export default Menus;
