const Services = [
  // Analysis
  {
    id: 1,
    name: "CSF Analysis",
    abbreviation: "CSF",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preparation: "none",
    specimen: "Whole Blood",
    template: 0,
    ro: null, // rule out
  },
  {
    id: 2,
    name: "FLUID ANALYSIS",
    abbreviation: "FA",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preparation: "none",
    specimen: null,
    template: 0,
  },
  {
    id: 3,
    name: "SEMINAL FLUID ANALYSIS",
    abbreviation: "SFA",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preparation: "No sexual contact for 3-5 day",
    specimen: "Sperm",
    template: 0,
    ro: null, // rule out
  },
  // Bacteriology
  {
    id: 4,
    name: "CULTURE AND SENSITIVITY /BLOOD",
    abbreviation: "CS-Bld",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preparation: "none",
    specimen: "Whole Blood",
    template: 1,
  },
  {
    id: 5,
    name: "ACID FAST BACILLI STAIN",
    abbreviation: "AFB",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "development",
    preparation: "none",
    specimen: "Sputum",
    template: 1,
  },
  {
    id: 6,
    name: "CULTURE AND SENSITIVITY  / BODY FLUID",
    abbreviation: "CS-bf",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preparation: "none",
    specimen: null,
    template: 1,
  },
  {
    id: 7,
    name: "CULTURE and SENSITIVITY/ Other",
    abbreviation: "CS-other",
    decSS: "",
    incSS: "",
    department: "laboratory",
    frequency: null,
    preparation: "none",
    specimen: "Whole Blood",
    template: 1,
  },

  // Chemistry
  {
    id: 9,
    name: "RANDOM BLOOD SUGAR",
    abbreviation: "RBS | CBG",
    decSS: "", // sign and symptoms if decrease
    incSS: "", // sign and symptoms if increase
    department: "laboratory",
    template: 3,
    frequency: "Monitoring",
    preference: "equal",
    preparation:
      "Use finger stick on side of finger not on tip to minimize pain and tissue juice. Don't smear blood on strip; allow drop to dry on strip.",
    specimen: "Serum",
    // to include in other tables
    // srp: 0,
    // products: [],
    // outsource: [],
    // rv: 2, // required volume
    // tv: 0, // total volume
  },
  {
    id: 10,
    name: "FASTING BLOOD SUGAR",
    abbreviation: "FBS",
    decSS: "",
    department: "laboratory",
    frequency: "Monitoring",
    incSS: "",
    preference: "equal",
    preparation: "Deep cough , no food or drinks before collection",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 11,
    name: "GLYCOSYLATED HEMOGLOBIN",
    abbreviation: "HBA1c",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "equal",
    preparation: "none",
    specimen: null,
    template: 3,
  },
  {
    id: 12,
    name: "ALANINE AMINOTRANSFERASE",
    abbreviation: "ALT/SGPT",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "equal",
    preparation: "none",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 13,
    name: "ASPARTATE AMINOTRANSFERASE",
    abbreviation: "AST/ SGOT",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "equal",
    preparation: "none",
    specimen: "Serum",
    template: 3,
  },
  // Lipid Profile
  {
    id: 14,
    name: "TOTAL CHOLESTEROL",
    abbreviation: "TC",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "equal",
    preparation: "10-12 hrs fasting",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 15,
    name: "TRIGLYCERIDES",
    abbreviation: "Tg",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "equal",
    preparation: "10-12 hrs fasting",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 16,
    name: "High Density Lipoprotein-Cholesterol",
    abbreviation: "HDL",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "equal",
    preparation: "10-12 hrs fasting",
    specimen: "serum",
    template: 3,
  },
  {
    id: 17,
    name: "Low Density Lipoprotein-Cholesterol",
    abbreviation: "LDL",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "equal",
    preparation: "10-12 hrs fasting",
    specimen: "serum",
    template: 3,
  },
  {
    id: 18,
    name: "VERY LOW DENSITY LIPOPROTIEN",
    abbreviation: "VLDL",
    decSS: "",
    department: "laboratory",
    frequency: "As necessary",
    incSS: "",
    preference: "equal",
    preparation: "none",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 19,
    name: "Chole/HDL Ratio",
    abbreviation: "Chole:HDL",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "equal",
    preparation: "none",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 20,
    name: "CREATININE",
    abbreviation: "CREA",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "SERUM",
    template: 3,
  },
  {
    id: 21,
    name: "BLOOD UREA NITROGEN",
    abbreviation: "BUN",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 22,
    name: "BLOOD URIC ACID",
    abbreviation: "BUA",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "FASTING 6 HOURS",
    specimen: "Serum",
    template: 3,
  },
  // Electrolytes
  {
    id: 23,
    name: "POTASSIUM",
    abbreviation: "K+",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "development",
    preparation:
      "Never give K to any patient who is not voiding. Limit K to 40 mEqs/L of fluid is added to IVF\nUsed for little injection (Death sentence)",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 24,
    name: "CHLORIDE",
    abbreviation: "Cl-",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 25,
    name: "SODIUM",
    abbreviation: "Na+",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "development",
    preparation: "none",
    specimen: "SERUM",
    template: 3,
  },
  {
    id: 26,
    name: "PHOSPHORUS, INORGANIC",
    abbreviation: "PO4",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "equal",
    preparation: "none",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 27,
    name: "CALCIUM",
    abbreviation: "Ca++",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 28,
    name: "CALCIUM,  IONIZED",
    abbreviation: "iCa++",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "equal",
    preparation: "none",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 29,
    name: "MAGNESUIM",
    abbreviation: "MG",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 30,
    name: "MAGNESUIM urine",
    abbreviation: "Mg-urine",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Urine",
    template: 3,
  },
  {
    id: 31,
    name: "ALKALINE PHOSPHATASE",
    abbreviation: "ALP",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 3,
  },
  // Bilirubin
  {
    id: 32,
    name: "TOTAL BILIRUBIN",
    abbreviation: "tBil",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "development",
    preparation: "none",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 33,
    name: "Direct Bilirubin",
    abbreviation: "dBil",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "development",
    preparation: "none",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 34,
    name: "Indirect Bilirubin",
    abbreviation: "iBil",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "development",
    preparation: "none",
    specimen: "Whole Blood",
    template: 3,
  },
  // TPAG
  {
    id: 35,
    name: "TOTAL PROTEIN",
    abbreviation: "TP",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "development",
    preparation: "none",
    specimen: "Other Body Fluids",
    template: 3,
  },
  {
    id: 36,
    name: "ALBUMIN",
    abbreviation: "ALB",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 3,
  },
  {
    id: 37,
    name: "GLOBULIN",
    abbreviation: "Glob",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 38,
    name: "ALBUMIN/ GLOBULIN RATIO",
    abbreviation: "A/G RATIO",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 39,
    name: "ALDOSTERONE",
    abbreviation: "ALD",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Whole Blood",
    template: 3,
  },
  {
    id: 40,
    name: "LACTOSE DEHYDROGENASE",
    abbreviation: "LH",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 3,
  },
  {
    id: 41,
    name: "GAMA GLUTAMYL TRANSFERAS PHOSPHATE",
    abbreviation: "GGTP",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "fecal",
    template: 3,
  },
  {
    id: 42,
    name: "PROLACTIN",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 43,
    name: "Total Iron",
    abbreviation: "Iron",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 44,
    name: "TOTAL IRON BINDING CAPACITY",
    abbreviation: "TIBC",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 45,
    name: "Urobilinogen",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 46,
    name: "ACID PHOSPHATASE",
    abbreviation: "ACP",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "EDTA",
    template: 3,
  },
  {
    id: 48,
    name: "Myoglobin",
    abbreviation: "MY",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 49,
    name: "BNP",
    abbreviation: "BNP",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 50,
    name: "Creatinine Phosphokinase",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 3,
  },
  {
    id: 51,
    name: "LIPASE",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "red top",
    template: 3,
  },
  {
    id: 52,
    name: "AMYLASE",
    abbreviation: "AMY",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 3,
  },
  // Coagulation
  {
    id: 53,
    name: "PROTHROMBIN TIME",
    abbreviation: "PT",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Citrated Plasma",
    template: 4,
  },
  {
    id: 54,
    name: "ACTIVATED PARTIAL THROMBOPLASTIN TIME",
    abbreviation: "aPTT",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Citrated Plasma",
    template: 4,
  },
  // Compatibility
  {
    id: 55,
    name: "ANTIBODY SCREENING",
    abbreviation: "ABS",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Whole Blood",
    template: 5,
  },
  {
    id: 56,
    name: "MATCH BLOOD",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "EDTA",
    template: 5,
  },
  {
    id: 57,
    name: "CROSSMATCHING",
    abbreviation: "x-matching",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "EDTA",
    template: 5,
  },
  // Hematology
  {
    id: 58,
    name: "COMPLETE BLOOD COUNT",
    abbreviation: "CBC",
    department: "laboratory",
    frequency: null,
    preference: "gender",
    preparation: "none",
    specimen: "EDTA",
    template: 6,
  },
  {
    id: 59,
    name: "ACTUAL PLATELET COUNT",
    abbreviation: "APC",
    department: "laboratory",
    frequency: null,
    preference: "equal",
    preparation: "none",
    specimen: "EDTA",
    template: 6,
  },
  {
    id: 60,
    name: "BLEEDING TIME",
    abbreviation: "BT",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 6,
  },
  {
    id: 61,
    name: "CLOTTING TIME",
    abbreviation: "CT",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Whole Blood",
    template: 6,
  },
  {
    id: 62,
    name: "RETICULOCYTE COUNT",
    abbreviation: "RETIC",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "EDTA",
    template: 6,
  },
  {
    id: 63,
    name: "ERYTHROCYTE SEDIMENTATION RATE",
    abbreviation: "ESR",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 6,
  },
  {
    id: 64,
    name: "Hemoglobin/Hematocrit",
    abbreviation: "HGB",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Whole Blood",
    template: 6,
  },
  {
    id: 65,
    name: "Hematocrit/Platelet",
    abbreviation: "HCT",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Whole Blood",
    template: 6,
  },
  // Miscellaneous : result are in words
  {
    id: 66,
    name: "BLOOD TYPING + RH",
    abbreviation: "BT/RH",
    department: "laboratory",
    frequency: "once",
    preparation: "none",
    specimen: null,
    template: 7,
  },
  {
    id: 67,
    name: "PREGNANCY TEST",
    abbreviation: "pt",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 7,
  },
  {
    id: 68,
    name: "HUMAN IMMUNODEFICIENCY VIRUS 1/2 Screening",
    abbreviation: "HIV 1/2 Screening",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 7,
  },
  {
    id: 69,
    name: "RAPID PLASMA REAGIN / SCREENING",
    abbreviation: "RPR/VDRL Screening",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 7,
  },
  {
    id: 71,
    name: "GLUCOSE 6 PHOSPHATE DEHYDROGENASE ASSAY",
    abbreviation: "G6PD SCREENING",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 7,
  },
  {
    id: 72,
    name: "GLUCOSE 6 PHOSPHATE DEHYDROGENASE CONFIRMATORY",
    abbreviation: "G6PD Confirmatory",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 7,
  },
  {
    id: 77,
    name: "DENGUE DUO (AG/AB) TEST",
    abbreviation: "DENGUE NS1, IgG & IgM",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "equal",
    preparation: "atleast a day of fever",
    specimen: "Serum/Plasma",
    template: 7,
  },
  {
    id: 80,
    name: "POTASSIUM HYDROXIDE SMEAR (10%)",
    abbreviation: "10% KOH",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 7,
  },
  {
    id: 82,
    name: "MALARIAL SMEAR",
    abbreviation: "MS",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "EDTA",
    template: 7,
  },
  {
    id: 131,
    name: "HEPATITIS A VIRUS SCREENING",
    abbreviation: "HAV SCREENING",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 7,
  },
  {
    id: 138,
    name: "ANTI HEPATITIS A VIRUS IGG",
    abbreviation: "ANTI HAV IGG",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 7,
  },
  {
    id: 139,
    name: "ANTI HEPATITIS A VIRUS IGM",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "not Vacinated with Hepatits B",
    specimen: "Serum",
    template: 7,
  },
  {
    id: 70,
    name: "HEPATITIS B SURFACE ANTIGEN / SCREENING",
    abbreviation: "HBsAg Screening",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 7,
  },
  {
    id: 95,
    name: "HEPATITIS B ENVELOPE ANTIGEN",
    abbreviation: "HBEA",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 96,
    name: "HEPATITIS B SURFACE ANTIGEN w/ TITER",
    abbreviation: "HBSA w/ titer",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 7,
  },
  {
    id: 97,
    name: "HEPATITIS C VIRUS / SCREENING",
    abbreviation: "HCV SCREENING",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 7,
  },
  // Fecalysis
  {
    id: 83,
    name: "FECALYSIS",
    abbreviation: "F/A",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 8,
  },
  {
    id: 84,
    name: "OCCULT BLOOD",
    abbreviation: "OB",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "no meat in food intake",
    specimen: "Stool",
    template: 8,
  },
  {
    id: 85,
    name: "APTS TEST",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Stool",
    template: 8,
  },
  // PAPs
  {
    id: 86,
    name: "Papanicolaou  Smear",
    abbreviation: "PAP's Smear",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Vaginal Smear",
    template: 9,
    description:
      "A procedure in which a small brush is used to gently remove cells from the surface of the cervix and the area around it so they can be checked under a microscope for cervical cancer or cell changes that may lead to cervical cancer.",
  },
  // PBS
  {
    id: 87,
    name: "PERIPHERAL BLOOD SMEAR",
    abbreviation: "PBS",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "EDTA",
    template: 10,
  },
  {
    id: 132,
    name: "ANTI HEPATITIS B CORE IGM",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "not Vacinated with Hepatits B",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 133,
    name: "ANTI HEPATITIS B CORE IGG",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "not Vacinated with Hepatits B",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 134,
    name: "ANTI HEPATITIS B ENVELOPE IGG",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "not Vacinated with Hepatits B",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 99,
    name: "ANTI HEPATITIS B ENVELOPE IGM",
    abbreviation: "aHBE-igm",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 140,
    name: "ANTI HEPATITIS C VIRUS/TITER",
    abbreviation: "ANTI-HCV",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  // Serology
  {
    id: 78,
    name: "CPK MM",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 79,
    name: "CPK-MB",
    abbreviation: "CK-MB",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 81,
    name: "CREATININE CLEARANCE",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: "As necessary",
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 73,
    name: "TESTOSTERONE",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 11,
  },
  {
    id: 74,
    name: "PANCREATIC CA",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 75,
    name: "ANTI-DS DNA",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 11,
  },
  {
    id: 76,
    name: "ESTROGEN & PROGESTERONE RECEPTOR W/ HER 2 NEU",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 7,
  },
  {
    id: 88,
    name: "CARCINOEMBRYONIC ANTIGEN/ COLORECTAL CA",
    abbreviation: "CEA",
    decSS: "",
    department: "laboratory",
    frequency: "As necessary",
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 89,
    name: "OVARIAN CA QUANTI",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: "As necessary",
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 90,
    name: "Estrogen/ Estradiol",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 91,
    name: "GRAM STAIN /Urine",
    abbreviation: "GS-urine",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Urine",
    template: 11,
  },
  {
    id: 93,
    name: "HELICOBACTER PYLORI  IGM (Quali)",
    abbreviation: "HPI-quali",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 11,
  },
  {
    id: 94,
    name: "HELICOBACTER PYLORI  IGM (Quanti)",
    abbreviation: "HPI-quanti",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 11,
  },
  {
    id: 101,
    name: "LEPTOSPIRA IGG/IGM",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 102,
    name: "LEUTINIZING HORMONE",
    abbreviation: "LH",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 103,
    name: "BREAST CA QUANTI",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 104,
    name: "PARATHYROID HORMONE",
    abbreviation: "PH",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 105,
    name: "PROGESTERONE",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 106,
    name: "PROSTATE SPECIFIC ANTIGEN",
    abbreviation: "PSA",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 11,
  },
  {
    id: 107,
    name: "ANTI-NUCLEATED ANTIGEN (screening)",
    abbreviation: "ANA ",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 11,
  },
  {
    id: 108,
    name: "ANTI-NUCLEATED ANTIGEN w/ titer",
    abbreviation: "ANA titer",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 11,
  },
  {
    id: 109,
    name: "Tatol CPK",
    abbreviation: "tCPK",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 98,
    name: "FOLLICLE STIMULATING HORMONE",
    abbreviation: "FSH",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 110,
    name: "THYROID STIMULATING HORMONE",
    abbreviation: "TSH",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 111,
    name: "FREE TRIIODOTHYRONINE",
    abbreviation: "FT3",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "equal",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 112,
    name: "FREE TETRAIODOTHYRONINE/ THYROXINE",
    abbreviation: "FT4",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 113,
    name: "Triiodothyronine",
    abbreviation: "T3",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 114,
    name: "TETRAIODOTHYRONINE/THYROXINE",
    abbreviation: "T4",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 115,
    name: "RHEUMATOID FACTOR",
    abbreviation: "RF",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 116,
    name: "TREPONEMA PALLIDUM HEME AGGLUTINATION / Confirmatory",
    abbreviation: "TPHA",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 117,
    name: "TREPONEMA PALLIDUM HEME AGGLUTINATION / titer",
    abbreviation: "TPHA titer",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 118,
    name: "TROPONIN I",
    abbreviation: "Trop I",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 119,
    name: "TROPONIN T",
    abbreviation: "Trop T",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 120,
    name: "TYPHOID /TYPHIDOT Test",
    abbreviation: "Typhoid IgG & IgM",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 7,
  },
  {
    id: 121,
    name: "TYPHOID /Widal Test",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 7,
  },
  {
    id: 122,
    name: "ESTROGEN",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 123,
    name: "D-Dimer",
    abbreviation: "D-Dimer",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 124,
    name: "COMPLEMENT 3",
    abbreviation: "C3",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 125,
    name: "COMPLEMENT 4",
    abbreviation: "C4",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 126,
    name: "FERRITIN",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 127,
    name: "CA-17.2",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 11,
  },
  {
    id: 128,
    name: "PROSTATIC ACID PHOSPHATASE",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 11,
  },
  {
    id: 129,
    name: "CORTISOL",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "equal",
    preparation: "none",
    specimen: null,
    template: 11,
  },
  {
    id: 130,
    name: "ALPHA FETO PROTEIN Quantitative",
    abbreviation: "AFP Q",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 145,
    name: "GRAM STAIN /BODY FLUIDS",
    abbreviation: "GS/bf",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Other Body Fluids",
    template: 11,
  },
  {
    id: 135,
    name: "ANTI-STREPTOLYSIN O TITER",
    abbreviation: "ASO",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 136,
    name: "BETA-HUMAN CHORIONIC GONADOTROPIN QUANTI",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 137,
    name: "C-REACTIVE PROTIEN/ QUALITATIVE",
    abbreviation: "CRP",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  {
    id: 141,
    name: "ANTI-CARDIOLIPIN IGG",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "Patient should fast at least 6 hrs",
    specimen: "Serum",
    template: 3,
  },
  {
    id: 142,
    name: "ANTI CARDIOLIPIN IGM",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: "Serum",
    template: 11,
  },
  // Urinalysis
  {
    id: 143,
    name: "URINALYSIS",
    abbreviation: "U/A",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preparation: "none",
    specimen: "Urine",
    template: 12,
  },
  {
    id: 144,
    name: "Glucose (Urine)",
    abbreviation: null,
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preparation: "none",
    specimen: "Urine",
    template: 12,
  },
  // Biopsy
  {
    id: 170,
    name: "FINE NEEDLE ASPIRATION BIOPSY",
    abbreviation: "FNAB",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 2,
  },
  {
    id: 172,
    name: "BIOPSY SMALL",
    abbreviation: "s-Biopsy",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 2,
  },
  {
    id: 173,
    name: "BIOPSY MEDIUM",
    abbreviation: "m-Biopsy",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 2,
  },
  {
    id: 174,
    name: "BIOPSY LARGE",
    abbreviation: "l-Biopsy",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 2,
  },
  {
    id: 175,
    name: "BIOPSY XLARGE",
    abbreviation: "xl-Biopsy",
    decSS: "",
    department: "laboratory",
    frequency: null,
    incSS: "",
    preference: "gender",
    preparation: "none",
    specimen: null,
    template: 2,
  },
  {
    id: 176,
    name: "Drug Test",
    abbreviation: "DT",
    department: "laboratory",
    preference: "equal",
    specimen: "urine",
    template: 13,
  },
  // Radiology
  {
    id: 201,
    name: "ElectroCardiogram",
    abbreviation: "ECG | EKG",
    department: "radiology",
    template: 0,
  },
  {
    id: 202,
    name: "Ultrasound",
    abbreviation: "utzd",
    department: "radiology",
    template: 1,
  },
  {
    id: 203,
    abbreviation: null,
    department: "radiology",
    name: "x-ray(Kidney  Urether Bladder )",
    template: 2,
  },
  {
    id: 204,
    name: "X-ray (Chest Anterior-Posterior)",
    abbreviation: "CHEST AP",
    department: "radiology",
    template: 2,
  },
  {
    id: 205,
    name: "x-ray (Chest Posterior-Anterior)",
    abbreviation: "CHEST PA",
    department: "radiology",
    template: 2,
  },
  {
    id: 206,
    name: "x-ray (Lumbo-Sacral)",
    abbreviation: null,
    department: "radiology",
    template: 2,
  },
  {
    id: 207,
    name: "x-ray (Pelvimetry /Pregnant)",
    abbreviation: null,
    department: "radiology",
    template: 2,
  },
  {
    id: 208,
    name: "x-ray (Plain Abdomen /supin)",
    abbreviation: null,
    department: "radiology",
    template: 2,
  },
  {
    id: 209,
    name: "x-ray (Rib Cage)",
    abbreviation: null,
    department: "radiology",
    template: 2,
  },
  {
    id: 210,
    name: "x-ray (Skull AP)",
    abbreviation: null,
    department: "radiology",
    template: 2,
  },
  {
    id: 211,
    name: "x-ray (Skull Lateral)",
    abbreviation: null,
    department: "radiology",
    template: 2,
  },
  {
    id: 212,
    name: "x-ray (T-cage)",
    abbreviation: null,
    department: "radiology",
    template: 2,
  },
  {
    id: 213,
    name: "x-ray (Thoraco-Lumbar )",
    abbreviation: null,
    department: "radiology",
    template: 2,
  },
  {
    id: 214,
    name: "x-ray (Varioum Enema)",
    abbreviation: null,
    department: "radiology",
    template: 2,
  },
  {
    id: 215,
    name: "x-ray (Lateral View)",
    abbreviation: null,
    department: "radiology",
    template: 2,
  },
  {
    id: 216,
    name: "x-ray Intravenous Pyelogram",
    abbreviation: "x-ray(IVP)",
    department: "radiology",
    template: 2,
  },
  {
    id: 217,
    name: "x-ray(Kidney  Urether Bladder )",
    abbreviation: "x-ray KUB",
    department: "radiology",
    template: 2,
  },
];

export default Services;
