const parameters = [
  {
    id: 1,
    area_id: 1,
    name: "Mission, vision and objectives shall be in accordance with RA 4688",
    ao: null,
  },
  {
    id: 2,
    area_id: 1,
    name: "License to operate/ accreditation Certificate and other documents",
    ao: null,
  },
  {
    id: 3,
    area_id: 1,
    name: "Policy on continuing program for staff development and training*",
    ao: null,
  },
  {
    id: 4,
    area_id: 1,
    name: "Policy for hiring, orientation and promotion for all levels of personnel*",
    ao: null,
  },
  {
    id: 5,
    area_id: 1,
    name: "Policy for discipline, suspension, demotion and termination of personnel at all levels*",
    ao: null,
  },
  {
    id: 6,
    area_id: 1,
    name: "Policy on Management Review*",
    ao: null,
  },
  {
    id: 7,
    area_id: 1,
    name: "Procedures for handling complaints and client feedback*",
    ao: null,
  },
  {
    id: 8,
    area_id: 2,
    name: "The organizational chart shall be clearly structured.",
    ao: "Sec. VI B. 1(a) (p.5)",
  },
  {
    id: 9,
    area_id: 2,
    name: "Duties and responsibilities shall be clearly spelled out.",
    ao: "Sec. VI B. 1(a) (p.5)",
  },
  {
    id: 10,
    area_id: 2,
    name: "Adequate number of qualified personnel with documented training and experience to conduct the laboratory procedures performed.",
    ao: "Sec. VI B. 1(a) iii – iv. (p.5) ",
  },
  {
    id: 11,
    area_id: 2,
    name: "Authority to practice (if applicable)",
    ao: "(AO# 92 S. 2003)",
  },
  {
    id: 12,
    area_id: 2,
    name: "The head shall have administrative  and technical  supervision of the activities in the laboratory",
    ao: "(AO# 92 S. 2003)",
  },
  {
    id: 13,
    area_id: 2,
    name: "No Pathologist in the area",
    ao: null,
  },
  {
    id: 14,
    area_id: 2,
    name: "No Clinical Pathologist certified by PSP",
    ao: null,
  },
  {
    id: 15,
    area_id: 2,
    name: "In laboratories offering Clinical Pathology services only",
    ao: null,
  },
  {
    id: 16,
    area_id: 2,
    name: "In laboratories offering both Anatomic & Clinical Pathology",
    ao: null,
  },
  {
    id: 17,
    area_id: 2,
    name: "Medical Technologist staff (additional proof of qualifications - as applicable)",
    ao: null,
  },
  {
    id: 18,
    area_id: 3,
    name: "Program of proper maintenance and monitoring of physical plant and facilities",
    ao: "Sec. VI B.1 (h) iv. (p6)",
  },
  {
    id: 19,
    area_id: 3,
    name: "Policy guidelines on laboratory biosafety and biosecurity",
    ao: "Sec. VI B.1 (h) v. (p6)",
  },
  {
    id: 20,
    area_id: 3,
    name: "Procedures for the proper disposal of waste and hazardous/infectious substances that shall conform to the standards set by the DOH",
    ao: "Sec. VI B.1 (h) vi. (p6)",
  },
  {
    id: 21,
    area_id: 4,
    name: "Adequate number of operational equipment to provide the laboratory examinations that the laboratory is licensed for.",
    ao: "Sec. VI B.1 (b) i. (p5) ",
  },
  {
    id: 22,
    area_id: 4,
    name: "Program for calibration, preventive maintenance and repair for the equipment.",
    ao: "Sec. VI B.1 (b) ii. (p5)",
  },
  {
    id: 23,
    area_id: 4,
    name: "Contingency plan in case of equipment breakdown",
    ao: "Sec. VI B.1 (b) iii. (p5)",
  },
  {
    id: 24,
    area_id: 5,
    name: "Adequate supply of properly stored and inventoried reagents and supplies for the laboratory examinations to be provided",
    ao: "Sec. VI B.1 (c) i.-ii. (p5)",
  },
  {
    id: 25,
    area_id: 5,
    name: "Reagents and supplies are stored under the required conditions. Adequate storage facilities such as refrigerators for perishable reagents and supplies.",
    ao: "Sec. VI B.1 (c)iii. (p5)",
  },
  {
    id: 26,
    area_id: 5,
    name: "Appropriate storage area/technique for flammable, combustible and hazardous chemical/reagents",
    ao: "Sec. VI B.1 (h) v.-vi. (p6)",
  },
  {
    id: 27,
    area_id: 6,
    name: "Administrative policies & procedures for provision of laboratory services and for the operation and maintenance of the laboratory",
    ao: "Sec. VI B.1 (d) (p5)",
  },
  {
    id: 28,
    area_id: 6,
    name: "Technical procedures of services provided in each section are available",
    ao: "Sec. VI B.1 (e) (p6)",
  },
  {
    id: 29,
    area_id: 7,
    name: "Procedures for the receipt and performance of routine and STAT requests for laboratory examinations (If applicable)",
    ao: "Sec. VI B.1 (g) i (p6)",
  },
  {
    id: 30,
    area_id: 7,
    name: "Procedures for reporting of results of routine and STAT laboratory examinations (If applicable)",
    ao: "Sec. VI B.1 (g) ii. (p6)",
  },
  {
    id: 31,
    area_id: 7,
    name: "All laboratory reports on various examinations of specimens shall bear the name of the pathologist or designated associate who shall be responsible for the reliability of the results. The reports shall bear the name of the registered medical technologist(s) who performed the examinations and duly signed by that person(s). Electronic signatures will be permitted in accordance to the Ecommerce law.",
    ao: "Sec. VI B.1 (g)iii. (p6)",
  },
  {
    id: 32,
    area_id: 7,
    name: "Procedures for reporting of work load, quality control, inventory control, etc.",
    ao: "Sec. VI B.1 (g) iv (p6)",
  },
  {
    id: 33,
    area_id: 7,
    name: "Procedure for reporting and analysis of incidents, adverse events, etc.",
    ao: "Sec. VI B.1 (g) v (p6)",
  },
  {
    id: 34,
    area_id: 7,
    name: "The retention of records of the laboratory shall follow standards promulgated by the Department of Health (DC# 70 s. 1996) and/or competent professional Organizations",
    ao: "Sec. VI B.1 (g).vi. (p6)",
  },
  {
    id: 35,
    area_id: 8,
    name: "Policy on Quality Assurance Program and Continuous Quality Improvement",
    ao: "Sec. VI B.1 (f).i. (p6)",
  },
  {
    id: 36,
    area_id: 8,
    name: "Participation in an External Quality Assessment Program (EQAP) administered by the designated National Reference Laboratories (NRL) or other EQAP approved by the BHFS-DOH",
    ao: "Sec. VI B.1 (f).ii. (p6)",
  },
  {
    id: 37,
    area_id: 9,
    name: "Policy on referral and outsourcing of examinations.",
    ao: "Sec. VI B.1.i. (p6)",
  },
];

module.exports = parameters;
