const products = [
  {
    _id: "64a6689c6a31f087ea1498d9",
    id: 1,
    supplierId: { 63: 5200, 2: 150, 6: 12 }, //companyId //BranchId
    avatar: "img/product.png",
    name: "Accumedia",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: false,
    packages: {
      pack: {
        // e.q: 4 bottle's / pack
        u: "btl", //unit
        q: 4, // quantity
      },
      btl: {
        // e.q: 25 ml/ bottle
        v: 250, // volume
        u: "ml", //unit
      },
    },
    conversion: { btl: 500, pack: 4 },
    category: null,
    isConsumable: true,
    created_at: "2018-11-27 09:18:07",
    updated_at: "2020-11-29 13:12:05",
  },
  {
    _id: "64a6689c6a31f087ea149944",
    id: 2,
    supplierId: { 6: 321 },
    avatar: "img/product.png",
    name: "Asiagel",
    subname: "BAP/CAP",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: null, u: "pc/s", q: 10 } },
    conversion: null,
    category: null,
    isConsumable: true,

    created_at: "2018-11-27 09:18:07",
    updated_at: "2020-11-29 13:12:05",
  },
  {
    _id: "64a6689c6a31f087ea149954",
    id: 3,
    supplierId: { 2: 150 },
    avatar: "img/product.png",
    name: "Asiagel",
    subname: "BAP/MAC",
    barcode: null,
    revert: true,
    halt: true,
    VATable: true,
    packages: { pack: { v: null, u: "pc/s", q: 10 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2018-12-12 02:01:02",
    updated_at: "2019-12-09 22:37:53",
  },
  {
    id: 4,
    supplierId: null,
    avatar: "img/product.png",
    name: "Bactefast",
    subname: "Blood Agar Plate",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: null, u: "pc/s", q: 10 } },
    conversion: null,
    category: null,
    isConsumable: true,

    created_at: "2018-12-19 02:24:11",
    updated_at: "2019-12-01 08:56:57",
  },
  {
    id: 5,
    supplierId: null,
    avatar: "img/product.png",
    name: "Bactefast",
    subname: "Chocolate Agar Plate",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: null, u: "pc/s", q: 10 } },
    conversion: null,
    category: null,
    isConsumable: true,

    created_at: "2018-12-19 02:27:00",
    updated_at: "2019-11-30 19:13:24",
  },
  {
    id: 6,
    supplierId: null,
    avatar: "img/product.png",
    name: "Bactefast",
    subname: "Mac Conkey Agar Plate",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: null, u: "pc/s", q: 10 } },
    conversion: null,
    category: null,
    isConsumable: true,

    created_at: "2018-12-19 02:29:00",
    updated_at: "2019-11-30 08:26:46",
  },
  {
    _id: "64a6689d6a31f087ea149985",
    id: 7,
    supplierId: null,
    avatar: "img/product.png",
    name: "Biorex",
    subname: "AMP",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { u: "ml", q: 150 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2018-12-19 02:30:52",
    updated_at: "2019-11-21 10:31:34",
  },
  {
    id: 8,
    supplierId: null,
    avatar: "img/product.png",
    name: "Biorex",
    subname: "Total",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { u: "ml", q: 125 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2018-12-19 02:32:02",
    updated_at: "2019-11-29 23:46:22",
  },
  {
    id: 9,
    supplierId: '{"6":32}',
    avatar: "product-brands/December2018/spanishbread.jpg",
    name: "Raptor",
    subname: null,
    barcode: null,
    revert: true,
    halt: true,
    VATable: true,
    packages: { box: { v: 0, u: "pc/s", q: 1, p: "Box" } },
    conversion: 1,
    category: null,
    isConsumable: true,
    remark: "this is a trial mode",
    created_at: "2018-12-21 23:51:41",
    updated_at: "2020-11-29 12:25:20",
  },
  {
    id: 10,
    supplierId: { 6: 32 },
    avatar: "img/product.png",
    name: "Biorex",
    subname: "Direct",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { u: "ml", q: 125 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2018-12-24 10:36:00",
    updated_at: "2020-11-29 12:25:20",
  },
  {
    id: 11,
    supplierId: null,
    avatar: "img/product.png",
    name: "Biorex",
    subname: "Arsenazo",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 125, u: "ml", q: 2 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2018-12-24 10:41:49",
    updated_at: "2019-11-15 12:27:47",
  },
  {
    id: 12,
    supplierId: null,
    avatar: "img/product.png",
    name: "Biorex",
    subname: "Total",
    barcode: "BRx123",
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 60, u: "ml x 6", q: null } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2018-12-24 10:47:31",
    updated_at: "2019-11-15 12:27:47",
  },
  {
    id: 13,
    supplierId: null,
    avatar: "img/product.png",
    name: "Biorex",
    subname: null,
    barcode: "12569",
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 120, u: "ml", q: 2 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2018-12-24 10:48:55",
    updated_at: "2019-11-15 12:27:47",
  },
  {
    id: 14,
    supplierId: null,
    avatar: "img/product.png",
    name: "Biorex",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { vial: { v: 5, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2018-12-24 10:50:49",
    updated_at: "2019-11-15 12:27:47",
  },
  {
    id: 15,
    supplierId: null,
    avatar: "img/product.png",
    name: "Biorex",
    subname: null,
    barcode: "jhy125",
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 60, u: "ml", q: 6 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2018-12-24 10:56:53",
    updated_at: "2019-11-15 12:27:47",
  },
  {
    id: 16,
    supplierId: null,
    avatar: "img/product.png",
    name: "Biorex",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 60, u: "ml", q: 2 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2018-12-24 10:58:15",
    updated_at: "2019-11-15 12:27:47",
  },
  {
    id: 17,
    supplierId: null,
    avatar: "img/product.png",
    name: "Spinreact",
    subname: '"CHOD/POD"',
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 250, u: "ml", q: 2 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2018-12-25 10:37:36",
    updated_at: "2019-11-15 12:27:47",
  },
  {
    id: 18,
    supplierId: null,
    avatar: "img/product.png",
    name: "Biorex",
    subname: "Xylidil Blue",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 60, u: "ml", q: 2 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2018-12-25 10:40:17",
    updated_at: "2019-11-15 12:27:47",
  },
  {
    id: 19,
    supplierId: null,
    avatar: "img/product.png",
    name: "Biorex",
    subname: "Multi",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { vial: { v: 3, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2018-12-28 00:56:32",
    updated_at: "2019-11-15 12:27:47",
  },
  {
    id: 20,
    supplierId: null,
    avatar: "img/product.png",
    name: "Biorex",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { vial: { v: 5, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2018-12-28 00:57:37",
    updated_at: "2019-11-15 12:27:47",
  },
  {
    id: 21,
    supplierId: null,
    avatar: "img/product.png",
    name: "Biorex",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 20, u: "ml", q: 5 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2018-12-28 00:58:26",
    updated_at: "2019-11-15 12:27:47",
  },
  {
    id: 22,
    supplierId: null,
    avatar: "img/product.png",
    name: "Biorex",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 60, u: "ml", q: 2, p: "Kit" } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-06 05:18:53",
    updated_at: "2019-11-15 12:27:47",
  },
  {
    id: 23,
    supplierId: null,
    avatar: "img/product.png",
    name: "Biorex",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 20, u: "ml", q: 5, p: "Kit" } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-06 05:19:10",
    updated_at: "2019-11-15 12:27:47",
  },
  {
    id: 24,
    supplierId: null,
    avatar: "img/product.png",
    name: "Boditech",
    subname: "I-Chroma",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 25, u: "pc/s", q: 1, p: "Kit" } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-07 03:34:40",
    updated_at: "2019-11-15 12:27:47",
  },
  {
    id: 25,
    supplierId: null,
    avatar: "img/product.png",
    name: "Boditech",
    subname: "I-Chroma",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 25, u: "pc/s", q: null } },
    conversion: null,
    category: null,
    isConsumable: true,

    created_at: "2019-01-07 04:52:59",
    updated_at: "2019-11-15 12:27:48",
  },
  {
    id: 26,
    supplierId: null,
    avatar: "img/product.png",
    name: "Boditech",
    subname: "I-Chroma",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 25, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-07 04:54:26",
    updated_at: "2019-11-15 12:27:48",
  },
  {
    id: 27,
    supplierId: null,
    avatar: "img/product.png",
    name: "Boditech",
    subname: "I-Chroma",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 25, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-07 04:55:10",
    updated_at: "2019-11-22 17:12:58",
  },
  {
    id: 28,
    supplierId: null,
    avatar: "img/product.png",
    name: "Boditech",
    subname: "I-Chroma",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 25, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-07 05:22:23",
    updated_at: "2019-11-22 16:49:02",
  },
  {
    id: 29,
    supplierId: null,
    avatar: "img/product.png",
    name: "Boditech",
    subname: "I-Chroma",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 25, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-07 05:27:37",
    updated_at: "2019-11-19 22:47:14",
  },
  {
    id: 30,
    supplierId: null,
    avatar: "img/product.png",
    name: "Boditech",
    subname: "I-Chroma",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 25, u: "pc/s", q: null } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-25 02:08:42",
    updated_at: "2019-11-15 12:27:48",
  },
  {
    id: 31,
    supplierId: null,
    avatar: "img/product.png",
    name: "Boditech",
    subname: "I-Chroma",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 25, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-25 02:15:17",
    updated_at: "2019-11-15 12:27:48",
  },
  {
    id: 32,
    supplierId: null,
    avatar: "img/product.png",
    name: "Boditech",
    subname: "I-Chroma",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 25, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-04 02:47:20",
    updated_at: "2019-11-15 12:27:48",
  },
  {
    id: 33,
    supplierId: null,
    avatar: "img/product.png",
    name: "Boditech",
    subname: "I-Chroma",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 25, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-25 03:16:50",
    updated_at: "2019-11-15 12:27:48",
  },
  {
    id: 34,
    supplierId: null,
    avatar: "img/product.png",
    name: "Boditech",
    subname: "I-Chroma",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 25, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-25 03:18:04",
    updated_at: "2019-11-15 12:27:48",
  },
  {
    id: 35,
    supplierId: null,
    avatar: "img/product.png",
    name: "Boditech",
    subname: "I-Chroma",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 25, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-25 03:19:41",
    updated_at: "2019-11-15 12:27:48",
  },
  {
    id: 36,
    supplierId: null,
    avatar: "img/product.png",
    name: "Boditech",
    subname: "Plus I-Chroma",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 25, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-25 03:22:02",
    updated_at: "2019-11-15 12:27:48",
  },
  {
    id: 37,
    supplierId: null,
    avatar: "img/product.png",
    name: "Boditech",
    subname: "I-Chroma",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 25, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-25 03:23:03",
    updated_at: "2019-11-15 12:27:48",
  },
  {
    id: 38,
    supplierId: null,
    avatar: "img/product.png",
    name: "Bluecross",
    subname: "Biostix",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 100, u: "Pcs", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-25 03:24:20",
    updated_at: "2019-11-15 12:27:48",
  },
  {
    id: 39,
    supplierId: null,
    avatar: "img/product.png",
    name: "Bluecross",
    subname: "Test Device (Serum/Plasma)",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: 40, u: "Pcs", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-25 03:25:53",
    updated_at: "2019-11-15 12:27:48",
  },
  {
    id: 40,
    supplierId: null,
    avatar: "img/product.png",
    name: "Branden",
    subname: "1.8ml/3.2% Sodium Citrate",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { tray: { v: 100, u: "Pcs", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-25 04:49:44",
    updated_at: "2019-11-15 12:27:48",
  },
  {
    id: 41,
    supplierId: null,
    avatar: "img/product.png",
    name: "BTS",
    subname: "Teflon",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 1, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-25 05:54:03",
    updated_at: "2019-11-15 12:27:48",
  },
  {
    id: 42,
    supplierId: null,
    avatar: "img/product.png",
    name: "BTS",
    subname: "Peristaltic",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 1, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-25 05:59:34",
    updated_at: "2019-11-15 12:27:48",
  },
  {
    id: 43,
    supplierId: null,
    avatar: "img/product.png",
    name: null,
    subname: "Carbon (CB51)",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 1, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-25 06:40:38",
    updated_at: "2019-11-15 12:27:48",
  },
  {
    id: 44,
    supplierId: null,
    avatar: "img/product.png",
    name: "Ceragem",
    subname: "Cera Check",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 50, u: "Pcs", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-25 06:42:41",
    updated_at: "2019-11-15 12:27:48",
  },
  {
    id: 45,
    supplierId: null,
    avatar: "img/product.png",
    name: "Ceragem",
    subname: "Cera Check Meter",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { set: { v: 1, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-25 07:05:37",
    updated_at: "2019-11-15 12:27:48",
  },
  {
    id: 46,
    supplierId: null,
    avatar: "img/product.png",
    name: "Asan Pharm",
    subname: "NS1/Ag/Ab",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 10, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-25 07:06:54",
    updated_at: "2019-11-15 12:27:48",
  },
  {
    id: 47,
    supplierId: null,
    avatar: "img/product.png",
    name: "Beijing Share-Sun",
    subname: "DH 505",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 1, u: "Unit", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-25 07:08:11",
    updated_at: "2019-11-15 12:27:48",
  },
  {
    id: 48,
    supplierId: null,
    avatar: "img/product.png",
    name: "Beijing Share-Sun",
    subname: "DH 505",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 400, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-25 07:09:55",
    updated_at: "2019-11-15 12:27:49",
  },
  {
    id: 49,
    supplierId: null,
    avatar: "img/product.png",
    name: "Beijing Share-Sun",
    subname: "DH 505",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 100, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-25 07:47:33",
    updated_at: "2019-11-15 12:27:49",
  },
  {
    id: 50,
    supplierId: null,
    avatar: "img/product.png",
    name: "Ca",
    subname: "DH 505",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 1, u: "pc/s", q: null } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-25 07:48:33",
    updated_at: "2019-11-15 12:27:49",
  },
  {
    id: 51,
    supplierId: null,
    avatar: "img/product.png",
    name: "Na+",
    subname: "DH 505",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 1, u: "pc/s", q: 1 } },
    conversion: 1,
    category: null,
    isConsumable: true,
    created_at: "2019-01-25 08:05:08",
    updated_at: "2019-11-15 12:27:49",
  },
  {
    id: 52,
    supplierId: null,
    avatar: "img/product.png",
    name: "K",
    subname: "DH 505",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 1, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-01-28 01:59:57",
    updated_at: "2019-11-15 12:27:49",
  },
  {
    id: 53,
    supplierId: null,
    avatar: "img/product.png",
    name: "Cl",
    subname: "DH 505",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 1, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 02:55:36",
    updated_at: "2019-11-15 12:27:49",
  },
  {
    id: 54,
    supplierId: null,
    avatar: "img/product.png",
    name: "pH",
    subname: "DH 505",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 1, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 02:56:56",
    updated_at: "2019-11-15 12:27:49",
  },
  {
    id: 55,
    supplierId: null,
    avatar: "img/product.png",
    name: "Reference",
    subname: "DH 505",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 1, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 02:57:47",
    updated_at: "2019-11-15 12:27:49",
  },
  {
    id: 56,
    supplierId: null,
    avatar: "img/product.png",
    name: "DH 505",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 10, u: "ml", q: 4 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 03:00:37",
    updated_at: "2019-11-15 12:27:49",
  },
  {
    id: 57,
    supplierId: null,
    avatar: "img/product.png",
    name: "DH 505",
    subname: "Reference Fill Solution",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { vial: { v: 10, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 03:06:42",
    updated_at: "2019-11-15 12:27:49",
  },
  {
    id: 58,
    supplierId: null,
    avatar: "img/product.png",
    name: "DH 505",
    subname: "Fill Solution",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { vial: { v: 10, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 03:07:44",
    updated_at: "2019-11-15 12:27:49",
  },
  {
    id: 59,
    supplierId: null,
    avatar: "img/product.png",
    name: "DH 505",
    subname: "Pump",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 1, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 03:08:51",
    updated_at: "2019-11-15 12:27:49",
  },
  {
    id: 60,
    supplierId: null,
    avatar: "img/product.png",
    name: "Trulab",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 60, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 03:10:22",
    updated_at: "2019-11-15 12:27:49",
  },
  {
    id: 61,
    supplierId: null,
    avatar: "img/product.png",
    name: "Wondfo",
    subname: "MET/THC",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 25, u: "Pcs", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 03:13:22",
    updated_at: "2019-11-15 12:27:49",
  },
  {
    id: 62,
    supplierId: null,
    avatar: "img/product.png",
    name: "Digisystem",
    subname: "Clinical DSC 1512T",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: null, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 03:53:19",
    updated_at: "2019-11-15 12:27:49",
  },
  {
    id: 63,
    supplierId: null,
    avatar: "img/product.png",
    name: "Trulab",
    subname: "Plate/Sealer",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 1, u: "pc/s", q: 1 } },
    conversion: 1,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 03:56:24",
    updated_at: "2019-11-15 12:27:49",
  },
  {
    id: 64,
    supplierId: null,
    avatar: "img/product.png",
    name: "Easylite",
    subname: "Bi-level QC",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 10, u: "ml", q: 2 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 03:57:51",
    updated_at: "2019-11-15 12:27:49",
  },
  {
    id: 65,
    supplierId: null,
    avatar: "img/product.png",
    name: "Easylite",
    subname: "Expand",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 800, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:02:51",
    updated_at: "2019-11-15 12:27:49",
  },
  {
    id: 66,
    supplierId: null,
    avatar: "img/product.png",
    name: "Easylite",
    subname: "Kit",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 1, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:04:34",
    updated_at: "2019-11-15 12:28:46",
  },
  {
    id: 67,
    supplierId: null,
    avatar: "img/product.png",
    name: "Easylite",
    subname: "Na+",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 1, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:05:52",
    updated_at: "2019-11-15 12:28:46",
  },
  {
    id: 68,
    supplierId: null,
    avatar: "img/product.png",
    name: "Easylite",
    subname: "K",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 1, u: "pc/s", q: null } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:06:59",
    updated_at: "2019-11-15 12:28:46",
  },
  {
    id: 69,
    supplierId: null,
    avatar: "img/product.png",
    name: "Easylite",
    subname: "Cl",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 1, u: "pc/s", q: null } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:09:18",
    updated_at: "2019-11-15 12:28:46",
  },
  {
    id: 70,
    supplierId: null,
    avatar: "img/product.png",
    name: "Easylite",
    subname: "Ca",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 1, u: "pc/s", q: null } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:10:40",
    updated_at: "2019-11-15 12:28:46",
  },
  {
    id: 71,
    supplierId: null,
    avatar: "img/product.png",
    name: "Easylite",
    subname: "Reference Housing",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 1, u: "Set", q: null } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:15:06",
    updated_at: "2019-11-15 12:28:46",
  },
  {
    id: 72,
    supplierId: null,
    avatar: "img/product.png",
    name: "Branden",
    subname: "EDTA, Glass",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { tray: { v: 2, u: "ml", q: 100 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:16:50",
    updated_at: "2019-11-15 12:27:50",
  },
  {
    id: 73,
    supplierId: null,
    avatar: "img/product.png",
    name: "Care Plus",
    subname: "EDTA Microtainer",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { tray: { v: null, u: "ml", q: 100 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:23:00",
    updated_at: "2019-11-15 12:27:50",
  },
  {
    id: 74,
    supplierId: null,
    avatar: "img/product.png",
    name: "AHG",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { vial: { v: 10, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:34:44",
    updated_at: "2019-11-15 12:27:50",
  },
  {
    id: 75,
    supplierId: null,
    avatar: "img/product.png",
    name: "Anti A",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { vial: { v: 10, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:35:52",
    updated_at: "2019-11-15 12:27:50",
  },
  {
    id: 76,
    supplierId: null,
    avatar: "img/product.png",
    name: "Anti B",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { vial: { v: 10, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:37:03",
    updated_at: "2019-11-15 12:27:50",
  },
  {
    id: 77,
    supplierId: null,
    avatar: "img/product.png",
    name: "Anti D",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { vial: { v: 10, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:37:55",
    updated_at: "2019-11-15 12:27:50",
  },
  {
    id: 78,
    supplierId: null,
    avatar: "img/product.png",
    name: "Liss/RAM",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { vial: { v: 10, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:39:05",
    updated_at: "2019-11-15 12:27:50",
  },
  {
    id: 79,
    supplierId: null,
    avatar: "img/product.png",
    name: null,
    subname: "Filter",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 24, u: "pc/s", q: 24 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:40:52",
    updated_at: "2019-11-15 12:28:46",
  },
  {
    id: 80,
    supplierId: null,
    avatar: "img/product.png",
    name: "Dr. Choice",
    subname: "Examination Medium",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: 100, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:43:25",
    updated_at: "2019-11-15 12:27:50",
  },
  {
    id: 81,
    supplierId: null,
    avatar: "img/product.png",
    name: "Gluco Plus",
    subname: "Orange, 50g",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 50, u: "g", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:47:14",
    updated_at: "2019-11-15 12:27:50",
  },
  {
    id: 82,
    supplierId: null,
    avatar: "img/product.png",
    name: "Gluco Plus",
    subname: "Orange, 75g",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 75, u: "g", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:49:25",
    updated_at: "2019-11-15 12:27:50",
  },
  {
    id: 83,
    supplierId: null,
    avatar: "img/product.png",
    name: "Gluco Plus",
    subname: "Cola, 75g",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 75, u: "g", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:50:30",
    updated_at: "2019-11-15 12:27:50",
  },
  {
    id: 84,
    supplierId: null,
    avatar: "img/product.png",
    name: "Gluco Plus",
    subname: "Orange, 100g",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 100, u: "g", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:51:47",
    updated_at: "2019-11-15 12:27:50",
  },
  {
    id: 85,
    supplierId: null,
    avatar: "img/product.png",
    name: "Golden Vac",
    subname: "Gel/Clot Activator",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { tray: { v: 3, u: "ml", q: 100 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:53:21",
    updated_at: "2019-11-15 12:27:50",
  },
  {
    id: 86,
    supplierId: null,
    avatar: "img/product.png",
    name: "Golden Vac",
    subname: "EDTA",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { tray: { v: 2, u: "ml", q: 100 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:56:50",
    updated_at: "2019-11-15 12:27:50",
  },
  {
    id: 87,
    supplierId: null,
    avatar: "img/product.png",
    name: "UV",
    subname: "Halogen",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 6, u: "volts", q: 10 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 04:59:10",
    updated_at: "2019-11-15 12:28:46",
  },
  {
    id: 88,
    supplierId: null,
    avatar: "img/product.png",
    name: "Microscope",
    subname: "Halogen",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 6, u: "volts", q: 10 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 05:00:25",
    updated_at: "2019-11-15 12:28:46",
  },
  {
    id: 89,
    supplierId: null,
    avatar: "img/product.png",
    name: "Digisystem",
    subname: "Reader",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pc: { v: 1, u: "pc/s", q: null } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 05:03:13",
    updated_at: "2019-11-15 12:28:46",
  },
  {
    id: 90,
    supplierId: null,
    avatar: "img/product.png",
    name: "Himedia",
    subname: "G.C. Base",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 500, u: "g", q: 1 } }, // Jar
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 05:05:20",
    updated_at: "2019-11-15 12:28:46",
  },
  {
    id: 91,
    supplierId: null,
    avatar: "img/product.png",
    name: "Himedia",
    subname: "Mac Conkey",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 500, u: "g", q: 1 } }, // Jar,
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 05:06:22",
    updated_at: "2019-11-15 12:28:47",
  },
  {
    id: 92,
    supplierId: null,
    avatar: "img/product.png",
    name: "Himedia",
    subname: "Shigella",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 500, u: "g", q: 1 } }, // Jar,
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 05:08:52",
    updated_at: "2019-11-15 12:28:47",
  },
  {
    id: 93,
    supplierId: null,
    avatar: "img/product.png",
    name: "Improve",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: 100, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 05:11:33",
    updated_at: "2019-11-15 12:27:51",
  },
  {
    id: 94,
    supplierId: null,
    avatar: "img/product.png",
    name: "Trulab",
    subname: "Sterile, 1ul",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 10, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 05:16:45",
    updated_at: "2019-11-15 12:27:51",
  },
  {
    id: 95,
    supplierId: null,
    avatar: "img/product.png",
    name: "Trulab",
    subname: "Sterile, 10ul",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 10, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 06:21:05",
    updated_at: "2019-11-15 12:28:47",
  },
  {
    id: 96,
    supplierId: null,
    avatar: "img/product.png",
    name: "CE",
    subname: "Sterile, 10ul",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: 500, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 06:22:31",
    updated_at: "2019-11-15 12:27:51",
  },
  {
    id: 97,
    supplierId: null,
    avatar: "img/product.png",
    name: "Ishio",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: 100, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 06:24:38",
    updated_at: "2019-11-15 12:27:51",
  },
  {
    id: 98,
    supplierId: null,
    avatar: "img/product.png",
    name: "Insight",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 100, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 06:26:33",
    updated_at: "2019-11-15 12:27:51",
  },
  {
    id: 99,
    supplierId: null,
    avatar: "img/product.png",
    name: "Insight",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 100, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 06:27:38",
    updated_at: "2019-11-15 12:27:51",
  },
  {
    id: 100,
    supplierId: null,
    avatar: "img/product.png",
    name: "Intec",
    subname: "Test Card (Serum/Plasma)",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 40, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 06:32:56",
    updated_at: "2019-11-15 12:27:51",
  },
  {
    id: 101,
    supplierId: null,
    avatar: "img/product.png",
    name: "Intec",
    subname: "Test Card (Serum/Plasma)",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 40, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 06:34:14",
    updated_at: "2019-11-15 12:27:51",
  },
  {
    id: 102,
    supplierId: null,
    avatar: "img/product.png",
    name: "Intec",
    subname: "Test Strip (Serum/Plasma)",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 50, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,

    created_at: "2019-02-04 06:35:25",
    updated_at: "2019-11-15 12:27:51",
  },
  {
    id: 103,
    supplierId: null,
    avatar: "img/product.png",
    name: "Intec",
    subname: "Combo Card",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 40, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,

    created_at: "2019-02-04 06:39:03",
    updated_at: "2019-11-15 12:27:51",
  },
  {
    id: 104,
    supplierId: null,
    avatar: "img/product.png",
    name: "Intec",
    subname: "Anti-TP/Test Card (Serum/Plasma)",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 40, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,

    created_at: "2019-02-04 06:40:51",
    updated_at: "2019-11-15 12:27:51",
  },
  {
    id: 105,
    supplierId: null,
    avatar: "img/product.png",
    name: "Intec",
    subname: "Anti-TP/Test Strip (Serum/Plasma)",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 50, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 06:42:26",
    updated_at: "2019-11-15 12:27:51",
  },
  {
    id: 106,
    supplierId: null,
    avatar: "img/product.png",
    name: "Labmate",
    subname: "10-100ul",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: 1, u: "Unit", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 06:44:13",
    updated_at: "2019-11-15 12:28:47",
  },
  {
    id: 107,
    supplierId: null,
    avatar: "img/product.png",
    name: "LPI",
    subname: "ESR",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 10, u: "pc/s", q: 1 } },
    conversion: 1,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 06:45:38",
    updated_at: "2019-11-15 12:27:51",
  },
  {
    id: 108,
    supplierId: null,
    avatar: "img/product.png",
    name: "Lumiquick",
    subname: "Urine",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 40, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 06:47:57",
    updated_at: "2019-11-15 12:27:51",
  },
  {
    id: 109,
    supplierId: null,
    avatar: "img/product.png",
    name: "Lumiquick",
    subname: "Urine/Serum",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 40, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 06:49:35",
    updated_at: "2019-11-15 12:27:51",
  },
  {
    id: 110,
    supplierId: null,
    avatar: "img/product.png",
    name: null,
    subname: "AFB Stain Set",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: 250, u: "Test", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 06:53:59",
    updated_at: "2019-11-15 12:27:51",
  },
  {
    id: 111,
    supplierId: null,
    avatar: "img/product.png",
    name: null,
    subname: "Drabkins Reagent",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 500, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:00:44",
    updated_at: "2019-11-15 12:27:52",
  },
  {
    id: 112,
    supplierId: null,
    avatar: "img/product.png",
    name: null,
    subname: "Gram Stain Set",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 200, u: "Test", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:01:59",
    updated_at: "2019-11-15 12:27:52",
  },
  {
    id: 113,
    supplierId: null,
    avatar: "img/product.png",
    name: null,
    subname: "Hayem's Solution",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 500, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:03:43",
    updated_at: "2019-11-15 12:27:52",
  },
  {
    id: 114,
    supplierId: null,
    avatar: "img/product.png",
    name: null,
    subname: "Hemaquick Stain Set",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 500, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:05:19",
    updated_at: "2019-11-15 12:27:52",
  },
  {
    id: 115,
    supplierId: null,
    avatar: "img/product.png",
    name: null,
    subname: "Lugol's Iodine",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 250, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:07:06",
    updated_at: "2019-11-15 12:27:52",
  },
  {
    id: 116,
    supplierId: null,
    avatar: "img/product.png",
    name: null,
    subname: "Methanol AR",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 500, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:09:01",
    updated_at: "2019-11-15 12:27:52",
  },
  {
    id: 117,
    supplierId: null,
    avatar: "img/product.png",
    name: null,
    subname: "Methanol AR",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 1000, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:10:06",
    updated_at: "2019-11-15 12:27:52",
  },
  {
    id: 118,
    supplierId: null,
    avatar: "img/product.png",
    name: "Medic",
    subname: "75g",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 75, u: "g", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:11:08",
    updated_at: "2019-11-15 12:27:52",
  },
  {
    id: 119,
    supplierId: null,
    avatar: "img/product.png",
    name: null,
    subname: "Rees & Ecker",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 250, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:12:50",
    updated_at: "2019-11-15 12:27:52",
  },
  {
    id: 120,
    supplierId: null,
    avatar: "img/product.png",
    name: null,
    subname: "SSA 3%",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 125, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:14:49",
    updated_at: "2019-11-15 12:27:52",
  },
  {
    id: 121,
    supplierId: null,
    avatar: "img/product.png",
    name: null,
    subname: "WBC Diluting Fluid",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 250, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:16:10",
    updated_at: "2019-11-15 12:27:52",
  },
  {
    id: 122,
    supplierId: null,
    avatar: "img/product.png",
    name: null,
    subname: "NSS 85%",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 250, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:17:25",
    updated_at: "2019-11-15 12:28:47",
  },
  {
    id: 123,
    supplierId: null,
    avatar: "img/product.png",
    name: null,
    subname: "Potassium Hydroxide, KOH",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 250, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:18:55",
    updated_at: "2019-11-15 12:28:47",
  },
  {
    id: 124,
    supplierId: null,
    avatar: "img/product.png",
    name: "Merck",
    subname: "2, 2.5L",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 1000, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:21:48",
    updated_at: "2019-11-15 12:28:47",
  },
  {
    id: 125,
    supplierId: null,
    avatar: "img/product.png",
    name: "Merck",
    subname: "3, 2.5L",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 1000, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:27:05",
    updated_at: "2019-11-15 12:28:47",
  },
  {
    id: 126,
    supplierId: null,
    avatar: "img/product.png",
    name: "3M",
    subname: '1"',
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 1000, u: "mm", q: 10 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:32:38",
    updated_at: "2019-11-15 12:27:52",
  },
  {
    id: 127,
    supplierId: null,
    avatar: "img/product.png",
    name: null,
    subname: "Unground Edges 72",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: 72, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:36:10",
    updated_at: "2019-11-15 12:27:52",
  },
  {
    id: 128,
    supplierId: null,
    avatar: "img/product.png",
    name: "Mindray",
    subname: "BC3000 HGB",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 1, u: "Set", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:37:28",
    updated_at: "2019-11-15 12:27:52",
  },
  {
    id: 129,
    supplierId: null,
    avatar: "img/product.png",
    name: "Mindray",
    subname: "M30 Hematology",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 3, u: "ml", q: 3 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:40:09",
    updated_at: "2019-11-15 12:27:52",
  },
  {
    id: 130,
    supplierId: null,
    avatar: "img/product.png",
    name: "M30 - AA",
    subname: "Mindray",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: 1000, u: "ml", q: 20 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:41:33",
    updated_at: "2019-11-15 12:27:52",
  },
  {
    id: 131,
    supplierId: null,
    avatar: "img/product.png",
    name: "M30 Startter Kit - AA",
    subname: "Mindray",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { set: { v: null, u: "Liter", q: 5 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:44:12",
    updated_at: "2019-11-15 12:27:52",
  },
  {
    id: 132,
    supplierId: null,
    avatar: "img/product.png",
    name: "Mindray",
    subname: "M30 - CC",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: 100, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:46:01",
    updated_at: "2019-11-15 12:28:47",
  },
  {
    id: 133,
    supplierId: null,
    avatar: "img/product.png",
    name: "Mindray",
    subname: "M30 - AA",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: 100, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:49:13",
    updated_at: "2019-11-15 12:27:52",
  },
  {
    id: 134,
    supplierId: null,
    avatar: "img/product.png",
    name: "Mindray",
    subname: "M30 - AA",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 250, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:51:02",
    updated_at: "2019-11-15 12:27:53",
  },
  {
    id: 135,
    supplierId: null,
    avatar: "img/product.png",
    name: "Mindray",
    subname: "M30 - AA",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: 2000, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:52:54",
    updated_at: "2019-11-15 12:27:53",
  },
  {
    id: 136,
    supplierId: null,
    avatar: "img/product.png",
    name: "Mindray",
    subname: "BC3200",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pc: { v: null, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 07:56:44",
    updated_at: "2019-11-15 12:27:53",
  },
  {
    id: 137,
    supplierId: null,
    avatar: "img/product.png",
    name: "Mindray",
    subname: "BC3200",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { set: { v: 5, u: "Liter", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 08:06:25",
    updated_at: "2019-11-15 12:27:53",
  },
  {
    id: 138,
    supplierId: null,
    avatar: "img/product.png",
    name: "Mindray",
    subname: "Diff M52 - AA",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 250, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 08:07:38",
    updated_at: "2019-11-15 12:27:53",
  },
  {
    id: 139,
    supplierId: null,
    avatar: "img/product.png",
    name: "M52 - AA",
    subname: "Mindray",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: 1000, u: "ml", q: 20 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 08:09:31",
    updated_at: "2019-11-15 12:27:53",
  },
  {
    id: 140,
    supplierId: null,
    avatar: "img/product.png",
    name: "Mindray",
    subname: "LH M52 - AA",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 250, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 08:10:34",
    updated_at: "2019-11-15 12:27:53",
  },
  {
    id: 141,
    supplierId: null,
    avatar: "img/product.png",
    name: "Mindray",
    subname: "M52 - CC",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 50, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 08:11:29",
    updated_at: "2019-11-15 12:27:53",
  },
  {
    id: 142,
    supplierId: null,
    avatar: "img/product.png",
    name: "Mindray",
    subname: "Hematology M55",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 3, u: "ml", q: 3 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 08:12:37",
    updated_at: "2019-11-15 12:27:53",
  },
  {
    id: 143,
    supplierId: null,
    avatar: "img/product.png",
    name: "Trulab",
    subname: "Plain, Small 90x15mm",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 20, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 08:28:11",
    updated_at: "2019-11-15 12:27:53",
  },
  {
    id: 144,
    supplierId: null,
    avatar: "img/product.png",
    name: "Branden",
    subname: "Glass",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { tray: { v: 3, u: "ml", q: 100 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 08:36:56",
    updated_at: "2019-11-15 12:27:53",
  },
  {
    id: 145,
    supplierId: null,
    avatar: "img/product.png",
    name: "Branden",
    subname: "Glass",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { tray: { v: 5, u: "ml", q: 100 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 08:38:15",
    updated_at: "2019-11-15 12:27:53",
  },
  {
    id: 146,
    supplierId: null,
    avatar: "img/product.png",
    name: "KT 6400",
    subname: "Render",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: 1000, u: "ml", q: 20 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 08:40:00",
    updated_at: "2019-11-15 12:27:53",
  },
  {
    id: 147,
    supplierId: null,
    avatar: "img/product.png",
    name: "Render",
    subname: "KT 6400",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 250, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 08:40:53",
    updated_at: "2019-11-15 12:27:53",
  },
  {
    id: 148,
    supplierId: null,
    avatar: "img/product.png",
    name: "Render",
    subname: "KT 6400",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 50, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 08:46:29",
    updated_at: "2019-11-15 12:27:53",
  },
  {
    id: 149,
    supplierId: null,
    avatar: "img/product.png",
    name: "Uniper/Render",
    subname: "LG Paber",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 300, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 08:49:05",
    updated_at: "2019-11-15 12:27:53",
  },
  {
    id: 150,
    supplierId: null,
    avatar: "img/product.png",
    name: "Uniper/Render",
    subname: "LG Paber",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: 288, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-04 08:50:15",
    updated_at: "2019-11-15 12:27:53",
  },
  {
    id: 151,
    supplierId: null,
    avatar: "img/product.png",
    name: "Biorex",
    subname: "NCP",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { vial: { v: 1, u: "ml", q: null } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 05:45:48",
    updated_at: "2019-11-15 12:27:53",
  },
  {
    id: 152,
    supplierId: null,
    avatar: "img/product.png",
    name: "Render",
    subname: "PT",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 2, u: "ml", q: 10 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 05:49:12",
    updated_at: "2019-11-15 12:27:53",
  },
  {
    id: 153,
    supplierId: null,
    avatar: "img/product.png",
    name: "Biorex",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 2, u: "ml", q: 5 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 05:55:25",
    updated_at: "2019-11-15 12:27:53",
  },
  {
    id: 154,
    supplierId: null,
    avatar: "img/product.png",
    name: "Uniper/Render",
    subname: "Enterobacteriaceae",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 10, u: "Test", q: null } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 06:00:04",
    updated_at: "2019-11-15 12:27:54",
  },
  {
    id: 155,
    supplierId: null,
    avatar: "img/product.png",
    name: "Uniper/Render",
    subname: "Non Fermenters",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 10, u: "Test", q: null } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 06:02:12",
    updated_at: "2019-11-15 12:27:54",
  },
  {
    id: 156,
    supplierId: null,
    avatar: "img/product.png",
    name: "Uniper/Render",
    subname: "Streptococcus/Enterococcus",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 10, u: "Test", q: null } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 06:03:40",
    updated_at: "2019-11-15 12:28:47",
  },
  {
    id: 157,
    supplierId: null,
    avatar: "img/product.png",
    name: "Uniper/Render",
    subname: "Staphylococcus",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 10, u: "Test", q: null } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 06:05:10",
    updated_at: "2019-11-15 12:27:54",
  },
  {
    id: 158,
    supplierId: null,
    avatar: "img/product.png",
    name: "Uniper/Render",
    subname: "Adult",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: null, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 06:10:49",
    updated_at: "2019-11-15 12:27:54",
  },
  {
    id: 159,
    supplierId: null,
    avatar: "img/product.png",
    name: "Uniper/Render",
    subname: "Pedia",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: null, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 06:12:06",
    updated_at: "2019-11-15 12:28:47",
  },
  {
    id: 160,
    supplierId: null,
    avatar: "img/product.png",
    name: "Uniper/Render",
    subname: "Fungus",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 10, u: "Test", q: null } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 06:12:44",
    updated_at: "2019-11-15 12:27:54",
  },
  {
    id: 161,
    supplierId: null,
    avatar: "img/product.png",
    name: "Uniper/Render",
    subname: "i-Magic",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: 10, u: "pc/s", q: null } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 06:16:30",
    updated_at: "2019-11-15 12:28:47",
  },
  {
    id: 162,
    supplierId: null,
    avatar: "img/product.png",
    name: "Cobas/Roche",
    subname: "Sensitive",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: 5, u: "pc/s", q: null } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 06:17:53",
    updated_at: "2019-11-15 12:27:54",
  },
  {
    id: 163,
    supplierId: null,
    avatar: "img/product.png",
    name: "Spin React",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 240, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 06:19:46",
    updated_at: "2019-11-15 12:27:54",
  },
  {
    id: 164,
    supplierId: null,
    avatar: "img/product.png",
    name: "Spin React",
    subname: "Coagulation",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { tray: { v: 100, u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 06:23:58",
    updated_at: "2019-11-15 12:27:54",
  },
  {
    id: 165,
    supplierId: null,
    avatar: "img/product.png",
    name: null,
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 100, u: "ml", q: null } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 06:33:34",
    updated_at: "2019-11-15 12:28:47",
  },
  {
    id: 166,
    supplierId: null,
    avatar: "img/product.png",
    name: "Spin React",
    subname: '"CHOD/POD"',
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 250, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 06:36:23",
    updated_at: "2019-11-15 12:27:54",
  },
  {
    id: 167,
    supplierId: null,
    avatar: "img/product.png",
    name: "Spin React",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 150, u: "ml", q: 2 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 06:37:48",
    updated_at: "2019-11-15 12:27:54",
  },
  {
    id: 168,
    supplierId: null,
    avatar: "img/product.png",
    name: "Spin React",
    subname: '"GOD/POD"',
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 250, u: "ml", q: 2 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 06:39:10",
    updated_at: "2019-11-15 12:27:54",
  },
  {
    id: 169,
    supplierId: null,
    avatar: "img/product.png",
    name: "Spin React",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 150, u: "ml", q: 2 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 06:40:49",
    updated_at: "2019-11-15 12:27:54",
  },
  {
    id: 170,
    supplierId: null,
    avatar: "img/product.png",
    name: "Spin React",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 250, u: "ml", q: 2 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 06:42:16",
    updated_at: "2019-11-15 12:27:54",
  },
  {
    id: 171,
    supplierId: null,
    avatar: "img/product.png",
    name: "Spin React",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 300, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 06:43:32",
    updated_at: "2019-11-15 12:27:54",
  },
  {
    id: 172,
    supplierId: null,
    avatar: "img/product.png",
    name: "Spin React",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 300, u: "ml", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-02-07 06:44:30",
    updated_at: "2019-11-15 12:27:55",
  },
  {
    id: 173,
    supplierId: null,
    avatar: "img/product.png",
    name: "Stanbio Hema-screen Lab",
    subname: "Test Slide",
    barcode: null,
    revert: 0,
    halt: false,
    VATable: true,
    packages: { pack: { u: "pc/s", q: 100 } },
    conversion: 100,
    category: null,
    isConsumable: true,
    created_at: "2019-02-16 01:43:21",
    updated_at: "2019-11-15 12:27:55",
  },
  {
    id: 174,
    supplierId: null,
    avatar: "img/product.png",
    name: "Trulab",
    subname: "Yellow",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: null, u: "pc/s", q: 1000 } },
    conversion: 2,
    category: null,
    isConsumable: true,
    created_at: "2019-02-16 05:20:10",
    updated_at: "2019-11-15 12:27:55",
  },
  {
    id: 175,
    supplierId: null,
    avatar: "img/product.png",
    name: "Tru-Lab",
    subname: "Blue",
    barcode: "OS-0069",
    revert: 0,
    halt: false,
    VATable: true,
    packages: { pack: { v: 10, u: "ul", q: 1000 } },
    conversion: 1,
    category: null,
    isConsumable: true,
    created_at: "2019-02-16 05:25:17",
    updated_at: "2019-11-15 12:27:55",
  },
  {
    id: 176,
    supplierId: null,
    avatar: "img/product.png",
    name: "Trulab-Sterile",
    subname: "Neutral",
    barcode: null,
    revert: 0,
    halt: false,
    VATable: true,
    packages: { pack: { v: 1, u: "ul", q: 100 } },
    conversion: 1,
    category: null,
    isConsumable: true,
    created_at: "2019-02-16 05:38:27",
    updated_at: "2019-11-15 12:27:55",
  },
  {
    id: 177,
    supplierId: null,
    avatar: "img/product.png",
    name: "Surgitech",
    subname: null,
    barcode: "OS-0126",
    revert: 0,
    halt: false,
    VATable: true,
    packages: { box: { v: 200, u: "pc/s", q: 1 } },
    conversion: 1,
    category: null,
    isConsumable: true,
    created_at: "2019-02-17 14:21:15",
    updated_at: "2019-11-15 12:27:55",
  },
  {
    id: 178,
    supplierId: null,
    avatar: "img/product.png",
    name: "Trulab",
    subname: "22x22mm",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: null, u: "mm", q: null } },
    conversion: 1,
    category: null,
    isConsumable: true,
    created_at: "2019-02-21 03:03:07",
    updated_at: "2019-11-15 12:27:55",
  },
  {
    id: 179,
    supplierId: null,
    avatar: "img/product.png",
    name: "SD Urocolor",
    subname: "4 parameter",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { u: "pc/s", q: 100 } },
    conversion: 1,
    category: null,
    isConsumable: true,
    created_at: "2019-02-21 03:04:53",
    updated_at: "2019-11-15 12:27:55",
  },
  {
    id: 180,
    supplierId: null,
    avatar: "img/product.png",
    name: "SD Urocolor",
    subname: "10 parameter",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { u: "pc/s", q: 100 } },
    conversion: 1,
    category: null,
    isConsumable: true,
    created_at: "2019-02-21 03:07:16",
    updated_at: "2019-11-15 12:27:55",
  },
  {
    id: 181,
    supplierId: null,
    avatar: "img/product.png",
    name: "Easylyte",
    subname: "Daily",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 90, u: "ml", q: 1 } },
    conversion: 1,
    category: null,
    isConsumable: true,
    created_at: "2019-02-21 03:14:51",
    updated_at: "2019-11-15 12:27:55",
  },
  {
    id: 182,
    supplierId: null,
    avatar: "img/product.png",
    name: "CE",
    subname: "Sterile, 1ul",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: 500, u: "pc/s", q: null } },
    conversion: 1,
    category: null,
    isConsumable: true,
    created_at: "2019-02-21 03:17:38",
    updated_at: "2019-11-15 12:28:47",
  },
  {
    id: 183,
    supplierId: null,
    avatar: "img/product.png",
    name: "Trulab",
    subname: "Sterile",
    barcode: null,
    revert: 0,
    halt: false,
    VATable: true,
    packages: { box: { v: 60, u: "ml", q: 1 } },
    conversion: 1,
    category: null,
    isConsumable: true,
    created_at: "2019-02-21 03:18:37",
    updated_at: "2019-11-15 12:27:55",
  },
  {
    id: 184,
    supplierId: null,
    avatar: "img/product.png",
    name: "Terumo",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: null, u: "pc/s", q: 100 } },
    conversion: 1,
    category: null,
    isConsumable: true,
    created_at: "2019-02-21 05:14:13",
    updated_at: "2019-11-15 12:27:55",
  },
  {
    id: 185,
    supplierId: null,
    avatar: "img/product.png",
    name: "Terumo",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: null, u: "pc/s", q: 100 } },
    conversion: 1,
    category: null,
    isConsumable: true,

    created_at: "2019-02-21 05:14:43",
    updated_at: "2019-11-15 12:27:55",
  },
  {
    id: 186,
    supplierId: null,
    avatar: "img/product.png",
    name: "Trulab",
    subname: "Blue",
    barcode: null,
    revert: 0,
    halt: false,
    VATable: true,
    packages: { pack: { v: 500, u: "pc/s", q: 1 } },
    conversion: 1,
    category: null,
    isConsumable: true,
    created_at: "2019-02-21 05:19:57",
    updated_at: "2019-11-15 12:27:55",
  },
  {
    id: 187,
    supplierId: null,
    avatar: "img/product.png",
    name: "Trulab",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { box: { v: 1000, u: "pc/s", q: null } },
    conversion: 1,
    category: null,
    isConsumable: true,
    created_at: "2019-02-21 05:23:42",
    updated_at: "2019-11-15 12:27:55",
  },
  {
    id: 188,
    supplierId: null,
    avatar: "img/product.png",
    name: "Biorex",
    subname: null,
    barcode: null,
    revert: 0,
    halt: false,
    VATable: true,
    packages: { kit: { v: 120, u: "ml", q: null } },
    conversion: 1,
    category: null,
    isConsumable: true,
    created_at: "2019-02-21 05:27:00",
    updated_at: "2019-11-15 12:27:55",
  },
  {
    id: 189,
    supplierId: null,
    avatar: "img/product.png",
    name: "Biorex",
    subname: null,
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { kit: { v: 120, u: "ml", q: null } },
    conversion: 1,
    category: null,
    isConsumable: true,
    created_at: "2019-02-21 05:29:48",
    updated_at: "2019-11-15 12:27:55",
  },
  {
    id: 190,
    supplierId: null,
    avatar: "img/product.png",
    name: "Medic",
    subname: "Solution",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 500, u: "ml", q: null } },
    conversion: 1,
    category: null,
    isConsumable: true,
    created_at: "2019-02-21 07:00:07",
    updated_at: "2019-11-15 12:27:55",
  },
  {
    id: 191,
    supplierId: null,
    avatar: "img/product.png",
    name: "Medic",
    subname: "Solution",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { btl: { v: 1000, u: "ml", q: 1 } },
    conversion: 1,
    category: null,
    isConsumable: true,
    created_at: "2019-02-21 07:00:53",
    updated_at: "2019-11-15 12:28:47",
  },
  {
    id: 192,
    supplierId: null,
    avatar: "img/product.png",
    name: null,
    subname: "Flat (Blue)",
    barcode: null,
    revert: true,
    halt: false,
    VATable: true,
    packages: { pack: { v: null, u: "pc/s", q: null } },
    conversion: 1,
    category: null,
    isConsumable: true,
    created_at: "2019-02-21 07:40:24",
    updated_at: "2019-11-15 12:28:47",
  },
  {
    id: 193,
    supplierId: null,
    avatar: "img/product.png",
    name: "clover",
    subname: null,
    barcode: "A-087",
    revert: 0,
    halt: false,
    VATable: true,
    packages: { pack: { v: 50, u: "Pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: false,
    created_at: "2019-03-03 19:53:37",
    updated_at: "2019-11-15 12:28:47",
  },
  {
    id: 194,
    supplierId: null,
    avatar: "img/product.png",
    name: "NRIS CAPILLARY",
    subname: null,
    barcode: null,
    revert: 0,
    halt: false,
    VATable: true,
    packages: { box: { v: 100, u: "pc/s", q: 10 } },
    conversion: null,
    category: null,
    isConsumable: true,
    created_at: "2019-03-07 14:09:40",
    updated_at: "2019-11-15 12:27:56",
  },
  {
    id: 195,
    supplierId: null,
    avatar: "img/product.png",
    name: "Centrifuge 24P",
    subname: "Digisystem",
    barcode: null,
    revert: 0,
    halt: false,
    VATable: true,
    packages: { pack: { u: "pc/s", q: 1 } },
    conversion: null,
    category: null,
    isConsumable: false,
    created_at: "2019-03-08 15:32:32",
    updated_at: "2019-11-15 12:28:48",
  },
];
module.exports = products;
